# Configurations
title: 6b6f6c6a61's blog
tagline: a blog about security
description: a blog about security

author:
  name:           6b6f6c6a61
  url:            https://twitter.com/6b6f6c6a61
  email:          6b6f6c6a61@mailbox.org

plugins:
  - jekyll-paginate
  - jekyll-remote-theme

paginate: 5

remote_theme: vfvong/jekyll-theme-tao

categories_path: /categories/
tags_path: /tags/
