# Configurations
title: 6b6f6c6a61's blog
tagline: -
description: a blog about security

author:
  name:           6b6f6c6a61
  url:            https://twitter.com/6b6f6c6a61
  email:            -

plugins:
  - jekyll-paginate
  - jekyll-remote-theme

paginate: 2

remote_theme: vfvong/jekyll-theme-tao

categories_path: /categories/
tags_path: /tags/
